somador = 0 #AQUI EU COMEÇO EM ZERO PQ SE NÃO ELE VAI SOMAR A PARTIR DO UM, MESMO O UM NÃO ATENDENDO AS CONDIÇÕES
#ENTÃO EU COLOCO SOMAR A PARTIR DO ZERO PARA DEIXAR O PROGRAMA ANALIZAR O UM, SE NÃO DARIA 20668 O RESULTADO
contador = 0
for c in range(1, 501, 2):
    if c % 3 == 0:
        somador += c #ESTOU FALANDO ASSIM: SOMA PRA MIM CADA C QUE ATENDE A CONDIÇÃO IMPOSTA. ESSE É O ACUMULADOR
        contador += 1 #AQUI ESTOU FALANDO: CONTA PRA MIM QUANTAS VEZES TU VAI FAZER ESSE PROCESSO, POR FAVOR
        #O ACUMULADOR GERALMENTE SOMA O VALOR DA VARIAVEL EM QUESTÃO E O CONTADOR GERALMENTE SOMA 1 OU DIMINUI 1
print('A soma de todos os {} números impares multiplos de três entre um e quinhentos é {}.'.format(contador, somador))